# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45660f2eb866ff047999abf800dca33adf5e90e05f12f394143e99c0c654b8ac749071c99ad43d418094a7948bd939508692710e8c4bda24431b10af7a66d354

test:
  secret_key_base: ad686980eeab7a58829017f69738c896e8bed5926db7a3de07c6481a0460174d5c3a9b260d7aa3b11d77d91cb0a0bcc7c649177a77e675e05a7f737df3fc1e06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
